name: Compile Artifacts

on:
    workflow_call:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set up Python 3.x
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install plac
          export SASS_VERSION=1.53.0
          curl --silent --show-error --location https://github.com/sass/dart-sass/releases/download/${SASS_VERSION}/dart-sass-${SASS_VERSION}-linux-x64.tar.gz | tar --extract --gzip
          mv dart-sass/sass /usr/local/bin
      - name: Create artifacts directory
        run: mkdir -p artifacts
      - name: Compile artifacts from changed files
        # NOTE: the LIBGUIDES_GROUPS secret must be single-quoted because it
        # contains JSON like `{"groups":[{"slug":"foo","id":"999"},{…}]}`
        run: for f in $(git diff-tree --no-commit-id --name-only -r ${{ github.sha }});
          do
            python .github/workflows/compile.py "$f" '${{ secrets.LIBGUIDES_GROUPS }}' --github-commit ${{ github.repository }}/commit/${{ github.sha }};
          done
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: compile-${{ github.sha }}
          path: artifacts
