name: Deploy Artifacts

on:
  push:
    paths:
      - "**.scss"
      - "*.js"
      - "*.html"
      - "*.shtm"
  workflow_call:

jobs:
  compile:
    uses: ./.github/workflows/compile.yml
  deploy:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set up Python 3.x
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install plac pytest-playwright
          playwright install firefox
      - uses: actions/download-artifact@v3
        with:
          name: compile-${{ github.sha }}
          path: artifacts
      - run: mkdir playwright
      - name: Deploy artifacts
        id: deploy
        # NOTE: the LIBGUIDES_GROUPS secret must be single-quoted because it
        # contains JSON like `{"groups":[{"slug":"foo","id":"999"},{…}]}`
        run: |
          echo "STATUS=$(python .github/workflows/deploy.py ${{ secrets.ADMIN_BASE_URL }} ${{ secrets.ADMIN_USERNAME }} ${{ secrets.ADMIN_PASSWORD }} '${{ secrets.LIBGUIDES_GROUPS }}')" >> $GITHUB_OUTPUT
      - run: tree
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: deploy-${{ github.sha }}
          path: playwright
      - name: Check deploy output
        if: ${{ steps.deploy.outputs.STATUS }}
        run: |
          echo ${{ steps.deploy.outputs.STATUS }}
          exit 1
