name: Deploy Components

on:
  push:
    paths:
      - "**.scss"
      - "*.js"
      - "*.html"
      - "*.shtm"
  workflow_call:

jobs:
  compile:
    uses: ./.github/workflows/compile.yml
    secrets: inherit
  deploy:
    runs-on: ubuntu-latest
    needs: compile
    env:
      PLAYWRIGHT_VERSION: "1.39.0"
      PYTHON_VERSION: "3.11.6"
    container:
      image: mcr.microsoft.com/playwright/python:v${PLAYWRIGHT_VERSION}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set up Python $PYTHON_VERSION
        uses: actions/setup-python@v4
        with:
          python-version: "$PYTHON_VERSION"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright==${PLAYWRIGHT_VERSION} pytest-playwright
      - uses: actions/download-artifact@v3
        with:
          name: compile-${{ github.sha }}
          path: artifacts
      - name: Deploy components
        id: deploy
        env:
          USERNAME: ${{ secrets.ADMIN_USERNAME }}
          PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          GROUPS: ${{ secrets.LIBGUIDES_GROUPS }}
        run: pytest --slowmo 100 --video on --output playwright --base-url ${{ secrets.ADMIN_BASE_URL }} -sv .github/workflows/deploy.py
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: deploy-${{ github.sha }}
          path: playwright
